/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alexandresc;

import javax.swing.JOptionPane;

/**
 *
 * @author e227070
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuCadastro = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        BotaoMedico = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenuItem();
        CadastraPaciente = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultorio");

        menuArquivo.setText("MENU");

        BotaoMedico.setText("CADASTRO  MEDICO");
        BotaoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMedicoActionPerformed(evt);
            }
        });
        menuArquivo.add(BotaoMedico);

        Consulta.setText("AGENDA CONSULTA");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });
        menuArquivo.add(Consulta);

        CadastraPaciente.setText("CADASTRA PACIENTE");
        CadastraPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraPacienteActionPerformed(evt);
            }
        });
        menuArquivo.add(CadastraPaciente);

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        menuArquivo.add(Sair);

        menuCadastro.add(menuArquivo);

        menuSobre.setText("SOBRE");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuCadastro.add(menuSobre);

        setJMenuBar(menuCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMedicoActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedico tela = new TelaCadastroMedico(); // Cria o formulário de Cadastro
tela.show(); // Exibe o formulário de Cadastro.

    }//GEN-LAST:event_BotaoMedicoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "teste");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        // TODO add your handling code here:
        BuscaConsulta tela = new BuscaConsulta(); // Cria o formulário de Cadastro
tela.show();
    }//GEN-LAST:event_ConsultaActionPerformed

    private void CadastraPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraPacienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroPaciente tela = new TelaCadastroPaciente(); // Cria o formulário de Cadastro
tela.show();
    }//GEN-LAST:event_CadastraPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BotaoMedico;
    private javax.swing.JMenuItem CadastraPaciente;
    private javax.swing.JMenuItem Consulta;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuCadastro;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}
